config/routes.rb
Baseball425::Application.routes.draw do
  resources :pitching_seasons

  resources :batting_seasons

  resources :players

  resources :teams

  resources :batting_seasons
  resources :pitching_seasons
  resources :players
  resources :teams

  root :to => 'teams#index'

end

app/models/batting_season.rb
class BattingSeason < ActiveRecord::Base
  belongs_to :player
  attr_accessible :ab, :ba, :bb, :bb_percent, :cs, :doubles, :gidp, :gp, :hbp, :hr, :ibb, :jersey_number, :k_percent, :obp, :ops, :pa, :position, :r, :rbi, :sb, :season_order, :sf, :sh, :singles, :slg, :so, :tb, :team, :triples, :player_id
  def self.search(search)
    if search
      find(:all, :conditions => ['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/batting_seasons_controller.rb
class BattingSeasonsController < ApplicationController
  # GET /batting_seasons
  # GET /batting_seasons.json
  def index
    @batting_seasons = BattingSeason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @batting_seasons }
    end
  end

  # GET /batting_seasons/1
  # GET /batting_seasons/1.json
  def show
    @batting_season = BattingSeason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @batting_season }
    end
  end

  # GET /batting_seasons/new
  # GET /batting_seasons/new.json
  def new
    @batting_season = BattingSeason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @batting_season }
    end
  end

  # GET /batting_seasons/1/edit
  def edit
    @batting_season = BattingSeason.find(params[:id])
  end

  # POST /batting_seasons
  # POST /batting_seasons.json
  def create
    @batting_season = BattingSeason.new(params[:batting_season])

    respond_to do |format|
      if @batting_season.save
        format.html { redirect_to @batting_season, notice: 'Batting season was successfully created.' }
        format.json { render json: @batting_season, status: :created, location: @batting_season }
      else
        format.html { render action: "new" }
        format.json { render json: @batting_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /batting_seasons/1
  # PUT /batting_seasons/1.json
  def update
    @batting_season = BattingSeason.find(params[:id])

    respond_to do |format|
      if @batting_season.update_attributes(params[:batting_season])
        format.html { redirect_to @batting_season, notice: 'Batting season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @batting_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /batting_seasons/1
  # DELETE /batting_seasons/1.json
  def destroy
    @batting_season = BattingSeason.find(params[:id])
    @batting_season.destroy

    respond_to do |format|
      format.html { redirect_to batting_seasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/batting_seasons_helper.rb
module BattingSeasonsHelper
end

app/views/batting_seasons/_form.html.haml
= form_for @batting_season do |f|
  - if @batting_season.errors.any?
    #error_explanation
      %h2= "#{pluralize(@batting_season.errors.count, "error")} prohibited this batting_season from being saved:"
      %ul
        - @batting_season.errors.full_messages.each do |msg|
          %li= msg
  .control-group 
    = f.label "Player", :class => 'control-label'
    .controls
      = select :batting_season, :player_id, Player.all.collect {|p| [p.first_name + ' ' + p.last_name, p.id]}
  .field
    = f.label :season_order
    = f.number_field :season_order
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :ab
    = f.number_field :ab
  .field
    = f.label :gp
    = f.number_field :gp
  .field
    = f.label :pa
    = f.number_field :pa
  .field
    = f.label :singles
    = f.number_field :singles
  .field
    = f.label :doubles
    = f.number_field :doubles
  .field
    = f.label :triples
    = f.number_field :triples
  .field
    = f.label :hr
    = f.number_field :hr
  .field
    = f.label :tb
    = f.number_field :tb
  .field
    = f.label :r
    = f.number_field :r
  .field
    = f.label :rbi
    = f.number_field :rbi
  .field
    = f.label :bb
    = f.number_field :bb
  .field
    = f.label :ibb
    = f.number_field :ibb
  .field
    = f.label :so
    = f.number_field :so
  .field
    = f.label :hbp
    = f.number_field :hbp
  .field
    = f.label :sf
    = f.number_field :sf
  .field
    = f.label :sh
    = f.number_field :sh
  .field
    = f.label :gidp
    = f.number_field :gidp
  .field
    = f.label :sb
    = f.number_field :sb
  .field
    = f.label :cs
    = f.number_field :cs
  .field
    = f.label :ba
    = f.text_field :ba
  .field
    = f.label :obp
    = f.text_field :obp
  .field
    = f.label :slg
    = f.text_field :slg
  .field
    = f.label :ops
    = f.text_field :ops
  .field
    = f.label :k_percent
    = f.text_field :k_percent
  .field
    = f.label :bb_percent
    = f.text_field :bb_percent
  .actions
    = f.submit 'Save'

app/views/batting_seasons/edit.html.haml
%h1 Editing batting_season

= render 'form'

= link_to 'Show', @batting_season
\|
= link_to 'Back', batting_seasons_path

app/views/batting_seasons/index.html.haml
%h1 Batting Seasons

= form_tag batting_seasons_path, :method => 'get' do 
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil
%table
  %tr
    %th Name
    %th Team
    %th Season order
    %th Position
    %th Ab
    %th Gp
    %th Pa
    %th Singles
    %th Doubles
    %th Triples
    %th Hr
    %th Tb
    %th R
    %th Rbi
    %th Bb
    %th Ibb
    %th So
    %th Hbp
    %th Sf
    %th Sh
    %th Gidp
    %th Sb
    %th Cs
    %th Ba
    %th Obp
    %th Slg
    %th Ops
    %th K percent
    %th Bb percent
    %th
    %th
    %th

  - @batting_seasons.each do |batting_season|
    %tr
      %td= batting_season.player.full_name
      %td= batting_season.player.team.team_name
      %td= batting_season.season_order
      %td= batting_season.position
      %td= batting_season.ab
      %td= batting_season.gp
      %td= batting_season.pa
      %td= batting_season.singles
      %td= batting_season.doubles
      %td= batting_season.triples
      %td= batting_season.hr
      %td= batting_season.tb
      %td= batting_season.r
      %td= batting_season.rbi
      %td= batting_season.bb
      %td= batting_season.ibb
      %td= batting_season.so
      %td= batting_season.hbp
      %td= batting_season.sf
      %td= batting_season.sh
      %td= batting_season.gidp
      %td= batting_season.sb
      %td= batting_season.cs
      %td= batting_season.ba
      %td= batting_season.obp
      %td= batting_season.slg
      %td= batting_season.ops
      %td= batting_season.k_percent
      %td= batting_season.bb_percent
      %td= link_to 'Show', batting_season
      %td= link_to 'Edit', edit_batting_season_path(batting_season)
      %td= link_to 'Destroy', batting_season, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Batting season', new_batting_season_path

app/views/batting_seasons/new.html.haml
%h1 New batting_season

= render 'form'

= link_to 'Back', batting_seasons_path

app/views/batting_seasons/show.html.haml
%p#notice= notice


%p
  %b Season order:
  = @batting_season.season_order
%p
  %b Position:
  = @batting_season.position
%p
  %b Ab:
  = @batting_season.ab
%p
  %b Gp:
  = @batting_season.gp
%p
  %b Pa:
  = @batting_season.pa
%p
  %b Singles:
  = @batting_season.singles
%p
  %b Doubles:
  = @batting_season.doubles
%p
  %b Triples:
  = @batting_season.triples
%p
  %b Hr:
  = @batting_season.hr
%p
  %b Tb:
  = @batting_season.tb
%p
  %b R:
  = @batting_season.r
%p
  %b Rbi:
  = @batting_season.rbi
%p
  %b Bb:
  = @batting_season.bb
%p
  %b Ibb:
  = @batting_season.ibb
%p
  %b So:
  = @batting_season.so
%p
  %b Hbp:
  = @batting_season.hbp
%p
  %b Sf:
  = @batting_season.sf
%p
  %b Sh:
  = @batting_season.sh
%p
  %b Gidp:
  = @batting_season.gidp
%p
  %b Sb:
  = @batting_season.sb
%p
  %b Cs:
  = @batting_season.cs
%p
  %b Ba:
  = @batting_season.ba
%p
  %b Obp:
  = @batting_season.obp
%p
  %b Slg:
  = @batting_season.slg
%p
  %b Ops:
  = @batting_season.ops
%p
  %b K percent:
  = @batting_season.k_percent
%p
  %b Bb percent:
  = @batting_season.bb_percent

= link_to 'Edit', edit_batting_season_path(@batting_season)
\|
= link_to 'Back', batting_seasons_path