config/routes.rb
Baseball425::Application.routes.draw do
  resources :pitching_seasons

  resources :batting_seasons

  resources :players

  resources :teams

  resources :batting_seasons
  resources :pitching_seasons
  resources :players
  resources :teams

  root :to => 'teams#index'

end

app/models/pitching_season.rb
class PitchingSeason < ActiveRecord::Base
  belongs_to :player
  attr_accessible :babip, :bb, :bb_percent, :bk, :bs, :cg, :er, :era, :gp, :gs, :h, :hbp, :hld, :hr, :ibb, :jersey_number, :k, :k_percent, :l, :outs, :outs, :r, :season_order, :sho, :sv, :tbf, :team, :w, :whip, :wp, :player_id
  
  def self.search(search)
    if search
      find(:all, :conditions => ['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/pitching_seasons_controller.rb
class PitchingSeasonsController < ApplicationController
  # GET /pitching_seasons
  # GET /pitching_seasons.json
  def index
    @pitching_seasons = PitchingSeason.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pitching_seasons }
    end
  end

  # GET /pitching_seasons/1
  # GET /pitching_seasons/1.json
  def show
    @pitching_season = PitchingSeason.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pitching_season }
    end
  end

  # GET /pitching_seasons/new
  # GET /pitching_seasons/new.json
  def new
    @pitching_season = PitchingSeason.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pitching_season }
    end
  end

  # GET /pitching_seasons/1/edit
  def edit
    @pitching_season = PitchingSeason.find(params[:id])
  end

  # POST /pitching_seasons
  # POST /pitching_seasons.json
  def create
    @pitching_season = PitchingSeason.new(params[:pitching_season])

    respond_to do |format|
      if @pitching_season.save
        format.html { redirect_to @pitching_season, notice: 'Pitching season was successfully created.' }
        format.json { render json: @pitching_season, status: :created, location: @pitching_season }
      else
        format.html { render action: "new" }
        format.json { render json: @pitching_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pitching_seasons/1
  # PUT /pitching_seasons/1.json
  def update
    @pitching_season = PitchingSeason.find(params[:id])

    respond_to do |format|
      if @pitching_season.update_attributes(params[:pitching_season])
        format.html { redirect_to @pitching_season, notice: 'Pitching season was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pitching_season.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pitching_seasons/1
  # DELETE /pitching_seasons/1.json
  def destroy
    @pitching_season = PitchingSeason.find(params[:id])
    @pitching_season.destroy

    respond_to do |format|
      format.html { redirect_to pitching_seasons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pitching_seasons_helper.rb
module PitchingSeasonsHelper
end

app/views/pitching_seasons/_form.html.haml
= form_for @pitching_season do |f|
  - if @pitching_season.errors.any?
    #error_explanation
      %h2= "#{pluralize(@pitching_season.errors.count, "error")} prohibited this pitching_season from being saved:"
      %ul
        - @pitching_season.errors.full_messages.each do |msg|
          %li= msg

  .control-group 
    = f.label "Player", :class => 'control-label'
    .controls
      = select :pitching_season, :player_id, Player.all.collect {|p| [p.first_name + ' ' + p.last_name, p.id]}
  .field
    = f.label :season_order
    = f.number_field :season_order
  .field
    = f.label :gp
    = f.number_field :gp
  .field
    = f.label :gs
    = f.number_field :gs
  .field
    = f.label :w
    = f.number_field :w
  .field
    = f.label :l
    = f.number_field :l
  .field
    = f.label :sv
    = f.number_field :sv
  .field
    = f.label :bs
    = f.number_field :bs
  .field
    = f.label :hld
    = f.number_field :hld
  .field
    = f.label :outs
    = f.number_field :outs
  .field
    = f.label :outs
    = f.number_field :outs
  .field
    = f.label :tbf
    = f.number_field :tbf
  .field
    = f.label :h
    = f.number_field :h
  .field
    = f.label :r
    = f.number_field :r
  .field
    = f.label :er
    = f.number_field :er
  .field
    = f.label :hr
    = f.number_field :hr
  .field
    = f.label :k
    = f.number_field :k
  .field
    = f.label :bb
    = f.number_field :bb
  .field
    = f.label :ibb
    = f.number_field :ibb
  .field
    = f.label :hbp
    = f.number_field :hbp
  .field
    = f.label :cg
    = f.number_field :cg
  .field
    = f.label :sho
    = f.number_field :sho
  .field
    = f.label :wp
    = f.number_field :wp
  .field
    = f.label :bk
    = f.number_field :bk
  .field
    = f.label :era
    = f.text_field :era
  .field
    = f.label :whip
    = f.text_field :whip
  .field
    = f.label :k_percent
    = f.text_field :k_percent
  .field
    = f.label :bb_percent
    = f.text_field :bb_percent
  .field
    = f.label :babip
    = f.text_field :babip
  .actions
    = f.submit 'Save'

app/views/pitching_seasons/edit.html.haml
%h1 Editing pitching_season

= render 'form'

= link_to 'Show', @pitching_season
\|
= link_to 'Back', pitching_seasons_path

app/views/pitching_seasons/index.html.haml
%h1 Pitching Seasons

= form_tag pitching_seasons_path, :method => 'get' do 
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil

%table
  %tr
    %th Name
    %th Team
    %th Season order
    %th Gp
    %th Gs
    %th W
    %th L
    %th Sv
    %th Bs
    %th Hld
    %th Outs
    %th Outs
    %th Tbf
    %th H
    %th R
    %th Er
    %th Hr
    %th K
    %th Bb
    %th Ibb
    %th Hbp
    %th Cg
    %th Sho
    %th Wp
    %th Bk
    %th Era
    %th Whip
    %th K percent
    %th Bb percent
    %th Babip
    %th
    %th
    %th

  - @pitching_seasons.each do |pitching_season|
    %tr
      %td= pitching_season.player.full_name
      %td= pitching_season.player.team.team_name
      %td= pitching_season.season_order
      %td= pitching_season.gp
      %td= pitching_season.gs
      %td= pitching_season.w
      %td= pitching_season.l
      %td= pitching_season.sv
      %td= pitching_season.bs
      %td= pitching_season.hld
      %td= pitching_season.outs
      %td= pitching_season.outs
      %td= pitching_season.tbf
      %td= pitching_season.h
      %td= pitching_season.r
      %td= pitching_season.er
      %td= pitching_season.hr
      %td= pitching_season.k
      %td= pitching_season.bb
      %td= pitching_season.ibb
      %td= pitching_season.hbp
      %td= pitching_season.cg
      %td= pitching_season.sho
      %td= pitching_season.wp
      %td= pitching_season.bk
      %td= pitching_season.era
      %td= pitching_season.whip
      %td= pitching_season.k_percent
      %td= pitching_season.bb_percent
      %td= pitching_season.babip
      %td= link_to 'Show', pitching_season
      %td= link_to 'Edit', edit_pitching_season_path(pitching_season)
      %td= link_to 'Destroy', pitching_season, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Pitching season', new_pitching_season_path

app/views/pitching_seasons/new.html.haml
%h1 New pitching_season

= render 'form'

= link_to 'Back', pitching_seasons_path

app/views/pitching_seasons/show.html.haml
%p#notice= notice


%p
  %b Season order:
  = @pitching_season.season_order
%p
  %b Gp:
  = @pitching_season.gp
%p
  %b Gs:
  = @pitching_season.gs
%p
  %b W:
  = @pitching_season.w
%p
  %b L:
  = @pitching_season.l
%p
  %b Sv:
  = @pitching_season.sv
%p
  %b Bs:
  = @pitching_season.bs
%p
  %b Hld:
  = @pitching_season.hld
%p
  %b Outs:
  = @pitching_season.outs
%p
  %b Outs:
  = @pitching_season.outs
%p
  %b Tbf:
  = @pitching_season.tbf
%p
  %b H:
  = @pitching_season.h
%p
  %b R:
  = @pitching_season.r
%p
  %b Er:
  = @pitching_season.er
%p
  %b Hr:
  = @pitching_season.hr
%p
  %b K:
  = @pitching_season.k
%p
  %b Bb:
  = @pitching_season.bb
%p
  %b Ibb:
  = @pitching_season.ibb
%p
  %b Hbp:
  = @pitching_season.hbp
%p
  %b Cg:
  = @pitching_season.cg
%p
  %b Sho:
  = @pitching_season.sho
%p
  %b Wp:
  = @pitching_season.wp
%p
  %b Bk:
  = @pitching_season.bk
%p
  %b Era:
  = @pitching_season.era
%p
  %b Whip:
  = @pitching_season.whip
%p
  %b K percent:
  = @pitching_season.k_percent
%p
  %b Bb percent:
  = @pitching_season.bb_percent
%p
  %b Babip:
  = @pitching_season.babip

= link_to 'Edit', edit_pitching_season_path(@pitching_season)
\|
= link_to 'Back', pitching_seasons_path