config/routes.rb
Baseball425::Application.routes.draw do
  resources :pitching_seasons

  resources :batting_seasons

  resources :players

  resources :teams

  resources :batting_seasons
  resources :pitching_seasons
  resources :players
  resources :teams

  root :to => 'teams#index'

end

app/models/player.rb
class Player < ActiveRecord::Base
  has_one :pitching_season
  has_one :batting_season
  belongs_to :team
  attr_accessible :date_of_birth, :first_name, :height, :last_name, :weight, :team_id
  
  def full_name
    first_name + ' ' + last_name
  end

  def self.search(search)
    if search
      find(:all, :conditions => ['first_name LIKE ? OR last_name LIKE ?', "%#{search}%", "%#{search}%"])
    else
      find(:all)
  end

end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  # GET /players
  # GET /players.json
  def index
    @players = Player.search(params[:search])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @player = Player.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/new
  # GET /players/new.json
  def new
    @player = Player.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @player }
    end
  end

  # GET /players/1/edit
  def edit
    @player = Player.find(params[:id])
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(params[:player])

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render json: @player, status: :created, location: @player }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /players/1
  # PUT /players/1.json
  def update
    @player = Player.find(params[:id])

    respond_to do |format|
      if @player.update_attributes(params[:player])
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :first_name, :class => 'control-label'
    .controls
      = f.text_field :first_name, :class => 'text_field'
  .control-group
    = f.label :last_name, :class => 'control-label'
    .controls
      = f.text_field :last_name, :class => 'text_field'
  .control-group
    = f.label :date_of_birth, :class => 'control-label'
    .controls
      = f.date_select :date_of_birth, :start_year => 1955, :class => 'date_select'
  .control-group
    = f.label :height, :class => 'control-label'
    .controls
      = f.text_field :height, :class => 'text_field'
  .control-group
    = f.label :weight, :class => 'control-label'
    .controls
      = f.text_field :weight, :class => 'text_field'
  .control-group 
    = f.label "Team", :class => 'control-label'
    .controls
      = select :player, :team_id, Team.all.collect {|t| [t.team_name, t.id]}

  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), players_path, :class => 'btn'

app/views/players/edit.html.haml
- model_class = Player
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/players/index.html.haml
- model_class = Player
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize

= form_tag players_path, :method => 'get' do 
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", :name => nil

%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:first_name)
      %th= model_class.human_attribute_name(:last_name)
      %th= model_class.human_attribute_name(:date_of_birth)
      %th= model_class.human_attribute_name(:height)
      %th= model_class.human_attribute_name(:weight)
      %th= model_class.human_attribute_name(:team)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @players.each do |player|
      %tr
        %td= link_to player.id, player_path(player)
        %td= player.first_name
        %td= player.last_name
        %td= player.date_of_birth
        %td= player.height
        %td= player.weight
        %td= player.team.team_name
        %td= player.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_player_path(player), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), player_path(player), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_player_path, :class => 'btn btn-primary'

app/views/players/new.html.haml
- model_class = Player
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/players/show.html.haml
- model_class = Player
.page-header
  %h1=t '.title', :default => model_class.model_name.human

%p
  %strong= model_class.human_attribute_name(:first_name) + ':'
  %br
  = @player.first_name
%p
  %strong= model_class.human_attribute_name(:last_name) + ':'
  %br
  = @player.last_name
%p
  %strong= model_class.human_attribute_name(:date_of_birth) + ':'
  %br
  = @player.date_of_birth
%p
  %strong= model_class.human_attribute_name(:height) + ':'
  %br
  = @player.height
%p
  %strong= model_class.human_attribute_name(:weight) + ':'
  %br
  = @player.weight
%p
  %strong= model_class.human_attribute_name(:team_id) + ':'
  %br
  = @player.team_id

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), players_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_player_path(@player), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), player_path(@player), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'